path: /home/haoran/RL/src/
nodes:
  - node:
      name: rl_env
      package: rl_navigation
      path: /home/haoran/RL/src/rl_navigation/launch/bringup_training.launch.xml

monitors:
  - monitor:
      id: monitor_rl
      log: ./log.txt
      silent: False
      warning: 2  
      oracle:
        port: 8080
        url: 127.0.0.1
        action: nothing
      topics:
        - name: /cmd_vel_raw
          type: geometry_msgs.msg.Twist
          action: filter
          publishers:
            - rl_env

        - name: /scan_min
          type: std_msgs.msg.Float32
          action: log

        - name: /scan_front_min           # 新增：供 property 使用
          type: std_msgs.msg.Float32
          action: log

        - name: /odom
          type: nav_msgs.msg.Odometry
          action: log
